trigger:
- main
variables:
- name: netbootIP
  value: 10.1.30.4

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DG Modules Container Registry'
    command: 'login'
    addPipelineData: false
- script: ./build.sh $(netbootIP)
  displayName: 'Build ubuntu base image'
- task: Docker@2
  inputs:
    containerRegistry: 'DG Modules Container Registry'
    repository: 'planetexpress/ubuntu-base'
    command: 'Push'
    Dockerfile: 'Dockerfile'
    addPipelineData: false
    tags: '22.04'
